wandb_version: 1

_wandb:
  desc: null
  value:
    code_path: code/train.py
    python_version: 3.10.13
    cli_version: 0.16.2
    framework: huggingface
    huggingface_version: 4.37.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1706952531.048853
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      2:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      3:
      - 23
      4: 3.10.13
      5: 0.16.2
      6: 4.37.0
      8:
      - 5
      13: linux-x86_64
